# Generated by Django 5.2.9 on 2026-02-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_bookauthor_bookseries_item_isbn_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='provider_author_names',
            field=models.JSONField(blank=True, default=list, help_text='List of author names from provider search results'),
        ),
        migrations.AddField(
            model_name='item',
            name='provider_series_data',
            field=models.JSONField(blank=True, default=dict, help_text='Series data from provider (name, position, etc.)'),
        ),
    ]
