# Generated by Django 5.2.9 on 2026-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0117_fix_reopened_completed_tv_seasons"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_item_without_season_episode",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_item_with_season",
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_item_with_season_episode",
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("episode_number__isnull", True), ("season_number__isnull", True)
                ),
                fields=("media_id", "source", "media_type", "library_media_type"),
                name="unique_item_without_season_episode",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("episode_number__isnull", True), ("season_number__isnull", False)
                ),
                fields=(
                    "media_id",
                    "source",
                    "media_type",
                    "library_media_type",
                    "season_number",
                ),
                name="unique_item_with_season",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("episode_number__isnull", False), ("season_number__isnull", False)
                ),
                fields=(
                    "media_id",
                    "source",
                    "media_type",
                    "library_media_type",
                    "season_number",
                    "episode_number",
                ),
                name="unique_item_with_season_episode",
            ),
        ),
    ]
