# Generated by Django 5.2.9 on 2026-06-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0118_add_library_media_type_to_item_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="dropped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="dropped",
            field=models.BooleanField(default=False),
        ),
    ]
