# Generated by Django 5.2.9 on 2026-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0125_fix_episode_season_library_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("gpodder", "GPodder"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="itemproviderlink",
            name="provider",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("gpodder", "GPodder"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metadataproviderpreference",
            name="provider",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("gpodder", "GPodder"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("gpodder", "GPodder"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                default="tmdb",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="source",
            field=models.CharField(
                choices=[
                    ("tmdb", "The Movie Database"),
                    ("tvdb", "TheTVDB"),
                    ("mal", "MyAnimeList"),
                    ("mangaupdates", "MangaUpdates"),
                    ("igdb", "Internet Game Database"),
                    ("openlibrary", "Open Library"),
                    ("hardcover", "Hardcover"),
                    ("comicvine", "Comic Vine"),
                    ("bgg", "BoardGameGeek"),
                    ("musicbrainz", "MusicBrainz"),
                    ("pocketcasts", "Pocket Casts"),
                    ("gpodder", "GPodder"),
                    ("audiobookshelf", "Audiobookshelf"),
                    ("manual", "Manual"),
                ],
                default="tmdb",
                max_length=20,
            ),
        ),
    ]
