# Generated by Django 5.2.12 on 2026-05-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0012_radarr_sonarr_and_collection_source_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="collectionsourcestate",
            new_name="integration_user_id_dd5a02_idx",
            old_name="integration_user_id_d7f810_idx",
        ),
        migrations.RenameIndex(
            model_name="collectionsourcestate",
            new_name="integration_user_id_6e87f7_idx",
            old_name="integration_user_id_942e5a_idx",
        ),
    ]
