# Generated by Django 5.2.12 on 2026-06-09 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_gpodderaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorytellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(help_text='Storyteller server URL')),
                ('auth_token', models.TextField(blank=True, default='', help_text='Encrypted Storyteller access token')),
                ('finished_threshold', models.FloatField(default=0.95, help_text='Reading progress fraction (0-1) at which a book is marked read')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_broken', models.BooleanField(default=False)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storyteller_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storyteller account',
                'verbose_name_plural': 'Storyteller accounts',
            },
        ),
    ]
