# Generated by Django 5.2.9 on 2026-05-01 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


HOME_QUERY_DEFAULT_FILTERS = {
    "status": "In progress",
    "rating": "all",
    "collection": "all",
    "genre": "",
    "year": "",
    "release": "all",
    "source": "",
    "language": "",
    "country": "",
    "platform": "",
    "origin": "",
    "format": "",
    "author": "",
    "tag": "",
    "tag_exclude": "",
}

HOME_SORT_ASCENDING = {
    "upcoming",
    "episodes_left",
    "title",
}

ENABLED_HOME_MEDIA_TYPES = [
    "tv",
    "season",
    "movie",
    "anime",
    "manga",
    "game",
    "book",
    "comic",
    "boardgame",
    "music",
    "podcast",
]


def _enabled_media_types_for_user(user):
    enabled = []
    for media_type in ENABLED_HOME_MEDIA_TYPES:
        if getattr(user, f"{media_type}_enabled", False):
            enabled.append(media_type)
    return enabled


def _direction_for_sort(sort_by):
    return "asc" if sort_by in HOME_SORT_ASCENDING else "desc"


def _seeded_media_types_for_user(user):
    return [
        media_type
        for media_type in _enabled_media_types_for_user(user)
        if media_type != "tv"
    ]


def _default_sort_for_media_type(user, media_type):
    requested = getattr(user, "home_sort", "title") or "title"
    if requested != "upcoming":
        return requested
    if media_type == "season":
        return "upcoming"
    return "recent"


def _default_rows_for_user(user, HomeScreenRow):
    planned_mode = getattr(user, "show_planned_on_home", "disabled") or "disabled"
    rows = []

    for media_type in _seeded_media_types_for_user(user):
        sort_by = _default_sort_for_media_type(user, media_type)
        position = 0
        rows.append(
            HomeScreenRow(
                user_id=user.id,
                media_type=media_type,
                position=position,
                enabled=True,
                row_type="library_query",
                sort_by=sort_by,
                direction=_direction_for_sort(sort_by),
                filters=dict(HOME_QUERY_DEFAULT_FILTERS),
            ),
        )
        position += 1

        if planned_mode != "disabled":
            planned_filters = dict(HOME_QUERY_DEFAULT_FILTERS)
            planned_filters["status"] = "Planning"
            rows.append(
                HomeScreenRow(
                    user_id=user.id,
                    media_type=media_type,
                    position=position,
                    enabled=True,
                    row_type="library_query",
                    sort_by=sort_by,
                    direction=_direction_for_sort(sort_by),
                    filters=planned_filters,
                ),
            )

    return rows


def seed_home_screen_rows(apps, schema_editor):
    User = apps.get_model("users", "User")
    HomeScreenRow = apps.get_model("users", "HomeScreenRow")

    seeded_rows = []
    for user in User.objects.all().iterator():
        seeded_rows.extend(_default_rows_for_user(user, HomeScreenRow))

    if seeded_rows:
        HomeScreenRow.objects.bulk_create(seeded_rows)


def noop_reverse(_apps, _schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0009_add_customlist_public_slug"),
        ("users", "0089_remove_user_tv_sort_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeScreenRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("boardgame", "Board Game"),
                            ("music", "Music"),
                            ("podcast", "Podcast"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "row_type",
                    models.CharField(
                        choices=[
                            ("library_query", "Library Row"),
                            ("custom_list", "List / Smart List"),
                            ("recently_unrated", "Recently Played - Not Rated"),
                        ],
                        default="library_query",
                        max_length=32,
                    ),
                ),
                ("sort_by", models.CharField(default="title", max_length=32)),
                (
                    "direction",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        max_length=4,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_screen_rows",
                        to="lists.customlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_screen_rows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["media_type", "position", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "media_type", "position"],
                        name="users_homes_user_id_cd4c85_idx",
                    ),
                    models.Index(
                        fields=["user", "enabled"],
                        name="users_homes_user_id_25d0be_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "media_type__in",
                                [
                                    "tv",
                                    "season",
                                    "movie",
                                    "anime",
                                    "manga",
                                    "game",
                                    "book",
                                    "comic",
                                    "boardgame",
                                    "music",
                                    "podcast",
                                ],
                            )
                        ),
                        name="home_screen_row_media_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "row_type__in",
                                ["library_query", "custom_list", "recently_unrated"],
                            )
                        ),
                        name="home_screen_row_row_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("direction__in", ["asc", "desc"])),
                        name="home_screen_row_direction_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_home_screen_rows, noop_reverse),
    ]
