# Generated by Django 5.2.12 on 2026-05-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_add_jellyfin_settings'),
        ('users', '0092_rename_next_episode_air_date_label'),
    ]

    operations = [
    ]
