# Generated by Django 5.2.9 on 2026-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0093_user_session_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="import_frequency",
            field=models.CharField(
                choices=[
                    ("once", "One Time Import"),
                    ("daily", "Every Day"),
                    ("2days", "Every 2 Days"),
                ],
                default="once",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="import_mode",
            field=models.CharField(
                choices=[
                    ("new", "Only Sync New Items"),
                    ("overwrite", "Sync New Items and Overwrite Existing"),
                    ("watchlist", "Import Watchlist Data Only"),
                    ("update_collection", "Update Collection Metadata Only"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="import_time",
            field=models.CharField(default="00:00", max_length=5),
        ),
    ]
