# Generated by Django 5.2.9 on 2026-06-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0120_comicissue_historicalcomicissue_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("lists", "0009_add_customlist_public_slug"),
        ("users", "0100_quick_season_update_choices"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="homescreenrow",
            name="home_screen_row_media_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="last_search_type_valid",
        ),
        migrations.AlterField(
            model_name="homescreenrow",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("comicissue", "Comic Issue"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_search_type",
            field=models.CharField(
                choices=[
                    ("tv", "TV Show"),
                    ("season", "TV Season"),
                    ("episode", "Episode"),
                    ("movie", "Movie"),
                    ("anime", "Anime"),
                    ("manga", "Manga"),
                    ("game", "Game"),
                    ("book", "Book"),
                    ("comic", "Comic"),
                    ("comicissue", "Comic Issue"),
                    ("boardgame", "Board Game"),
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                ],
                default="tv",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="homescreenrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "media_type__in",
                        [
                            "tv",
                            "season",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "comicissue",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="home_screen_row_media_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "last_search_type__in",
                        [
                            "tv",
                            "movie",
                            "anime",
                            "manga",
                            "game",
                            "book",
                            "comic",
                            "comicissue",
                            "boardgame",
                            "music",
                            "podcast",
                        ],
                    )
                ),
                name="last_search_type_valid",
            ),
        ),
    ]
