# Generated by Django 5.2.9 on 2026-06-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0102_home_row_title_and_media_type_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stats_split_tv_anime",
            field=models.BooleanField(
                default=False,
                help_text="When anime is disabled in sidebar, show TVDB-tagged anime as a separate Anime bucket in Statistics.",
            ),
        ),
    ]
